'use client';
import { useEffect, useState } from 'react';
import DecisionLab from '../components/DecisionLab';

type Case={id:string;customer:string;amount:number;issue:string;reason:string;score:number;status:string;channel:string;nextAction:string;lastEvent:string;recoveredAmount:number;razorpayPaymentLinkId?:string|null};
type Analysis={diagnosis:string;action:string;confidence:number;recoveryProbability:number;expectedRecovery:number;attempts:number;hoursSinceLastAttempt:number;policy:{allowed:boolean;reason:string};rationale:string;timestamp:string};

export default function Home(){
 const [cases,setCases]=useState<Case[]>([]),[stats,setStats]=useState({atRisk:0,recoverable:0,recovered:0,recoveryRate:0}),[selected,setSelected]=useState<Case|null>(null),[analysis,setAnalysis]=useState<Analysis|null>(null),[trace,setTrace]=useState<string[]>(['Risk detected','Root cause pending','Policy check pending','Intervention pending','Stop condition: payment_link.paid']),[running,setRunning]=useState(false),[executing,setExecuting]=useState(false),[paymentLink,setPaymentLink]=useState<string|null>(null),[toolError,setToolError]=useState<string|null>(null),[rzpReady,setRzpReady]=useState(false);
 async function load(id?:string){const d=await fetch('/api/dashboard',{cache:'no-store'}).then(r=>r.json());setCases(d.cases);setStats(d.stats);setRzpReady(d.rzpConfigured);const c=d.cases.find((x:Case)=>x.id===(id??selected?.id))??d.cases[0];if(c){setSelected(c);const x=await fetch(`/api/recovery/${c.id}`,{cache:'no-store'}).then(r=>r.json());setAnalysis(x.analysis);}}
 useEffect(()=>{load();},[]);
 useEffect(()=>{if(!selected)return;const t=setInterval(()=>load(selected.id),4000);return()=>clearInterval(t);},[selected?.id]);
 async function selectCase(c:Case){setSelected(c);setPaymentLink(null);setToolError(null);const d=await fetch(`/api/recovery/${c.id}`,{cache:'no-store'}).then(r=>r.json());setAnalysis(d.analysis);setTrace(['Risk detected','Root cause: '+d.analysis.diagnosis,'Policy check: '+(d.analysis.policy.allowed?'approved':'blocked'),`Intervention: ${d.analysis.action}`,'Stop condition: payment_link.paid']);}
 async function executeTool(){if(!selected||!analysis)return;setExecuting(true);setToolError(null);if(analysis.action==='payment_link'){const r=await fetch('/api/razorpay/payment-link',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({caseId:selected.id})});const d=await r.json();if(!r.ok){setToolError(d.error||'Razorpay action failed');setTrace(t=>[...t,'Tool execution blocked: '+(d.error||'unknown error')]);}else{setPaymentLink(d.paymentLink?.short_url||null);setTrace(t=>[...t,'Razorpay Payment Link created','Awaiting payment_link.paid webhook']);await load(selected.id);}}else setTrace(t=>[...t,`Action ${analysis.action.replaceAll('_',' ')} scheduled under policy guardrails`]);setExecuting(false);}
 async function run(){setRunning(true);setTrace(['Batch started','Analyzing revenue-risk cases…','Calculating expected recovered ₹…','Applying policy guardrails…']);const d=await fetch('/api/recovery/batch',{method:'POST'}).then(r=>r.json());setTrace(['Batch completed',`${d.analyzed} cases analyzed · ${d.approved} interventions approved`,`Expected recovery: ₹${d.expectedRecovery.toLocaleString('en-IN')}`,'Audit events written','Stop conditions armed']);setRunning(false);await load(selected?.id);}
 const current=analysis??{diagnosis:'bank_timeout',action:'retry_upi',confidence:.91,recoveryProbability:.91,expectedRecovery:0,attempts:0,hoursSinceLastAttempt:0,policy:{allowed:true,reason:'policy_pass'},rationale:'Loading recovery decision…',timestamp:new Date().toISOString()};
 if(!selected)return <div className="shell"><main className="main"><div className="card">Loading REVIVE recovery control plane…</div></main></div>;
 return <div className="shell"><header className="topbar"><div className="brand"><span className="mark">↻</span><span>REVIVE</span><span className="muted">/ Revenue Recovery</span></div><div className="small">Agent status <span className="pill good">● guarded & online</span></div></header><main className="main">
 <section className="hero"><div><div className="eyebrow">AI Revenue Recovery Control Plane</div><h1 className="title">Recover the money that is <span className="accent">slipping away.</span></h1><p className="sub">Revive detects revenue at risk, diagnoses why it happened, ranks interventions by expected recovered ₹, enforces policy outside the AI layer, and stops when money is recovered or a guardrail says stop.</p></div><button className="btn" onClick={run} disabled={running}>{running?'Running recovery…':'Run recovery batch'}</button></section>
 <section className="grid"><Metric label="Revenue at risk" value={`₹${stats.atRisk.toLocaleString('en-IN')}`} delta={`${cases.filter(c=>c.status==='At risk').length} active cases`}/><Metric label="AI-identified recoverable" value={`₹${stats.recoverable.toLocaleString('en-IN')}`} delta="expected recovery value"/><Metric label="Recovered" value={`₹${stats.recovered.toLocaleString('en-IN')}`} delta="persisted & reconciled"/><Metric label="Recovery rate" value={`${stats.recoveryRate.toFixed(1)}%`} delta="based on recovered cash"/></section>
 <section className="two section"><div className="card"><div className="sectionTitle">Recovery queue <span className="small">· ranked by expected recovery</span></div><table className="table"><thead><tr><th>Customer</th><th>Exposure</th><th>Reason</th><th>AI score</th><th>Status</th></tr></thead><tbody>{cases.map(c=><tr key={c.id} onClick={()=>selectCase(c)} style={{cursor:'pointer'}}><td><b>{c.customer}</b><div className="small">{c.id} · {c.issue}</div></td><td>₹{c.amount.toLocaleString('en-IN')}</td><td>{c.reason}</td><td><span className={c.score>=80?'pill good':c.score>=60?'pill warn':'pill bad'}>{c.score}/100</span></td><td>{c.status}</td></tr>)}</tbody></table></div>
 {selected && (
  <DecisionLab caseId={selected.id} />
)}
 <div className="card"><div className="eyebrow">Agent decision</div><div className="bigMoney">₹{selected.amount.toLocaleString('en-IN')}</div><div className="small">{selected.customer} · {selected.issue}</div><div className="section"><div className="small">Recovery probability · {(current.recoveryProbability*100).toFixed(0)}%</div><div className="score"><span style={{width:`${current.recoveryProbability*100}%`}}/></div></div><div className="decisionGrid"><div><span>Diagnosis</span><b>{current.diagnosis.replaceAll('_',' ')}</b></div><div><span>Expected recovery</span><b>₹{current.expectedRecovery.toLocaleString('en-IN')}</b></div><div><span>Chosen action</span><b>{current.action.replaceAll('_',' ')}</b></div><div><span>Policy</span><b className={current.policy.allowed?'textGood':'textBad'}>{current.policy.allowed?'APPROVED':'BLOCKED'}</b></div></div><div className="rationale">{current.rationale}</div><button className="btn dark" style={{marginTop:14,width:'100%'}} onClick={executeTool} disabled={executing||!current.policy.allowed||selected.status==='Recovered'}>{executing?'Executing recovery tool…':current.action==='payment_link'?'Create Razorpay Payment Link':'Execute bounded recovery action'}</button>{toolError&&<div className="toolError">{toolError}</div>}{paymentLink&&<a className="paymentLink" href={paymentLink} target="_blank" rel="noreferrer">Open Razorpay Payment Link ↗</a>}<div className="small" style={{marginTop:12}}>Razorpay link: {selected.razorpayPaymentLinkId?'created':'not created'} · auto-refresh every 4s</div></div></section>
 <section className="two section"><div className="card"><div className="sectionTitle">Why Revive wins</div><Feature n="1" title="Diagnose before nudging" text="Bank timeout ≠ insufficient funds ≠ price hesitation. Each gets a different intervention." tag="AI"/><Feature n="2" title="Optimize expected recovery" text="Prioritizes expected recovered ₹, not the number of messages sent." tag="AI"/><Feature n="3" title="Bounded autonomy" text="Amount, frequency, cooldown, opt-out and escalation rules are enforced outside the AI layer." tag="Guarded"/><Feature n="4" title="Prove the money" text="Every decision, payment and webhook reconciliation is persisted." tag="Audit"/></div><div className="card" id="trace"><div className="sectionTitle">Execution trace <span className="small">· persistent</span></div><div className="timeline">{trace.map((t,i)=><Event key={i} title={t} text={i===0?'payment.failed → recovery exposure created':i===1?'Structured diagnosis generated':i===2?'Policy engine evaluated autonomy budget':i===3?'Tool action selected from allow-list':'Terminal event closes the recovery case'}/>)}</div></div></section>
 <section className="section"><div className="card architecture"><div><div className="eyebrow">Decision architecture</div><h2>AI proposes. Policy authorizes. Razorpay executes.</h2><p className="small">The AI is never the authority for a financial action. Revive converts AI output into a structured decision, validates it against deterministic guardrails, then calls an allow-listed payment tool and reconciles the result against a signed webhook.</p></div><div className="flow"><span>Event</span><i>→</i><span>AI diagnosis</span><i>→</i><span>Policy</span><i>→</i><span>Razorpay</span><i>→</i><span>Webhook</span></div></div></section><div className="footer">REVIVE · V4 Persistent Recovery · {rzpReady?'credentials configured':'credentials not configured'} · signed webhook + idempotent reconciliation</div></main></div>
}
function Metric({label,value,delta}:{label:string,value:string,delta:string}){return <div className="card"><div className="metricLabel">{label}</div><div className="metric">{value}</div><div className="delta">↗ {delta}</div></div>}
function Event({title,text}:{title:string,text:string}){return <div className="event"><span className="dot"/><div><b>{title}</b><p>{text}</p></div></div>}
function Feature({n,title,text,tag}:{n:string,title:string,text:string,tag:string}){return <div className="action"><div><b>{n}. {title}</b><div className="small">{text}</div></div><span className="pill good">{tag}</span></div>}
