import { guard } from '../api/policy';
import { getStore, withStore, StoredCase } from './store';
export type Diagnosis='bank_timeout'|'insufficient_funds'|'price_hesitation'|'promise_to_pay'|'issuer_decline';
export type Action='retry_upi'|'payment_link'|'promise_to_pay'|'escalate'|'no_action';
const diagnosisMap:Record<string,Diagnosis>={'Bank timeout':'bank_timeout','Insufficient funds':'insufficient_funds','Price hesitation':'price_hesitation','Promise to pay':'promise_to_pay','Issuer decline':'issuer_decline'};
function actionFor(c:StoredCase):Action{if(c.status==='Recovered')return'no_action';if(c.score<55)return'escalate';if(c.reason==='Bank timeout')return'retry_upi';if(c.reason==='Price hesitation')return'payment_link';if(c.reason==='Promise to pay')return'promise_to_pay';if(c.reason==='Insufficient funds')return'payment_link';return'escalate';}
function probability(score:number){return Math.min(.99,Math.max(.05,score/100));}
function rationale(c:StoredCase,a:Action){if(a==='retry_upi')return'Temporary bank timeout is usually retryable; wait for the cooldown before attempting the same rail again.';if(a==='payment_link')return'A fresh payment path reduces checkout friction and gives the customer a direct route to complete payment.';if(a==='promise_to_pay')return'The customer has indicated intent to pay, so a timed follow-up is lower friction than another payment attempt.';if(a==='no_action')return'Payment is already recovered. Revive stops immediately to prevent unnecessary customer contact.';return c.score<55?'Low recovery probability or exhausted retry budget; escalate instead of repeatedly contacting the customer.':'The case requires a safer intervention than autonomous retry.';}
export async function getCase(id:string){const s=await getStore();return s.cases.find(c=>c.id===id);}
export async function analyzeCase(c:StoredCase){const diagnosis=diagnosisMap[c.reason]??'issuer_decline';const action=actionFor(c);const attempts=c.id==='RC-1042'?1:c.id==='RC-1028'?3:0;const hoursSinceLastAttempt=c.id==='RC-1042'?3:c.id==='RC-1028'?5:4;const policy=guard({amount:c.amount,attempts,hoursSinceLastAttempt,reason:diagnosis});const allowed=action==='no_action'?false:policy.allowed;const confidence=probability(c.score);return{caseId:c.id,diagnosis,action,confidence,recoveryProbability:confidence,expectedRecovery:Math.round(c.amount*confidence),attempts,hoursSinceLastAttempt,policy:{...policy,allowed},rationale:rationale(c,action),timestamp:new Date().toISOString()};}
export async function rankCases(){const s=await getStore();const rows=s.cases.filter(c=>c.status==='At risk');const ranked=[];for(const c of rows)ranked.push({case:c,analysis:await analyzeCase(c)});return ranked.sort((a,b)=>b.analysis.expectedRecovery-a.analysis.expectedRecovery);}
export async function markRecovered(id:string,details?:{amount?:number;paymentLinkId?:string|null;paymentId?:string|null}){return withStore(s=>{const c=s.cases.find(x=>x.id===id);if(!c)return undefined;const amount=details?.amount??c.amount;c.status='Recovered';c.nextAction='No action — recovered';c.lastEvent='just now';c.recoveredAmount=amount;c.recoveredAt=new Date().toISOString();if(details?.paymentLinkId)c.razorpayPaymentLinkId=details.paymentLinkId;return c;});}
export async function createAction(caseId:string,type:string,status:string,expectedRecovery:number,externalId?:string){return withStore(s=>{const item={id:`ACT-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,caseId,type,status,expectedRecovery,externalId,executedAt:new Date().toISOString()};s.audits.unshift({id:`AUD-${Date.now()}`,caseId,eventType:'RECOVERY_ACTION',actor:'REVIVE',status:'success',detail:`${type} ${status}`,externalId,payload:item,createdAt:new Date().toISOString()});return item;});}
